"""Trigger SQL corpus: each rule_id maps to (sql, dialect_or_None)."""

TRIGGER_CORPUS = {
    "COMP-AUD-001": ("DELETE FROM audit_log WHERE action = 'LOGIN';", None),
    "COMP-CCPA-001": ("SELECT * FROM marketing_campaigns WHERE sale_date > '2024-01-01'", None),
    "COMP-GDPR-001": ("SELECT email, name FROM users WHERE id = 1;", None),
    "COMP-GDPR-002": ("SELECT * FROM DBLINK('host', 'query') AS t(id int);", None),
    "COMP-GDPR-003": ("DELETE FROM users WHERE id = 1;", None),
    "COMP-GDPR-004": ("INSERT INTO marketing (email) VALUES ('a@b.com');", None),
    "COMP-GDPR-005": ("SELECT /* dsar */ * FROM users", None),
    "COMP-GDPR-006": ("SELECT email, name FROM users WHERE role = 'admin';", None),
    "COMP-HIPAA-001": ("SELECT ssn, diagnosis, patient_name FROM medical_records;", None),
    "COMP-HIPAA-002": ("SELECT * FROM patients WHERE diagnosis = 'cancer';", None),
    "COMP-HIPAA-003": ("SELECT * FROM t WHERE encrypt=false AND patients.id = 1;", None),
    "COMP-PCI-001": ("SELECT * FROM payments WHERE card_number = '4111111111111111';", None),
    "COMP-PCI-002": ("INSERT INTO payments (card_number, cvv) VALUES ('4111111111111111', '123');", None),
    "COMP-PCI-003": ("SELECT * FROM transactions;", None),
    "COMP-RET-001": ("CREATE TABLE audit_log (id SERIAL PRIMARY KEY, action VARCHAR(20), performed_at TIMESTAMP DEFAULT NOW());", None),
    "COMP-SEC-001": ("CREATE TABLE users (password VARCHAR(100));", None),
    "COMP-SOX-001": ("DELETE FROM ledger WHERE id = 1;", None),
    "COMP-SOX-002": ("UPDATE financial_transactions SET status='approved' WHERE created_by='user';", None),
    "COST-ARCHIVE-001": ("SELECT * FROM events WHERE created_at < '2020-01-01';", None),
    "COST-BQ-001": ("SELECT * FROM project.dataset.table WHERE _PARTITIONTIME = TIMESTAMP('2024-01-01');", "bigquery"),
    "COST-BQ-002": ("SELECT * FROM project.dataset.table;", "bigquery"),
    "COST-BQ-003": ("SELECT (SELECT COUNT(*) FROM orders) AS a, (SELECT COUNT(*) FROM orders) AS b;", "bigquery"),
    "COST-CH-001": ("SELECT * FROM users WHERE id = 1;", "clickhouse"),
    "COST-COMPRESS-001": ("CREATE TABLE logs (id SERIAL, message TEXT, payload TEXT);", None),
    "COST-COMPUTE-001": ("SELECT * FROM users;", None),
    "COST-COMPUTE-002": ("SELECT ROW_NUMBER() OVER (ORDER BY id) FROM users;", None),
    "COST-CROSS-001": ("SELECT * FROM db1.users u JOIN db2.orders o ON u.id = o.user_id;", None),
    "COST-CROSS-002": ("SELECT * FROM users@us-east.rds.amazonaws.com;", None),
    "COST-CROSS-003": ("BEGIN DISTRIBUTED TRANSACTION;", None),
    "COST-IDX-001": ("CREATE INDEX idx1 ON users(email); CREATE INDEX idx2 ON users(email);", None),
    "COST-IDX-002": ("CREATE INDEX idx_a ON users(a); CREATE INDEX idx_b ON users(b); CREATE INDEX idx_c ON users(c);", None),
    "COST-IDX-003": ("SELECT email, name FROM users WHERE email = 'test@test.com';", None),
    "COST-IDX-004": ("CREATE INDEX idx ON users(email, name);", None),
    "COST-IO-001": ("SELECT * FROM (SELECT * FROM users ORDER BY name) sub;", None),
    "COST-MYSQL-001": ("SELECT * FROM users GROUP BY id;", "mysql"),
    "COST-NETWORK-001": ("SELECT * FROM users@remote_db;", None),
    "COST-ORA-001": ("SELECT /*+ FULL(users) */ * FROM users;", "oracle"),
    "COST-PAGE-001": ("SELECT * FROM users OFFSET 100000 LIMIT 10;", None),
    "COST-PAGE-002": ("SELECT * FROM users LIMIT 10 OFFSET 1001;", None),
    "COST-PAGE-003": ("SELECT COUNT(*) FROM users;", None),
    "COST-PARTITION-001": ("SELECT * FROM events WHERE created_at > '2024-01-01';", None),
    "COST-PRESTO-001": ("SELECT * FROM users ORDER BY name;", "presto"),
    "COST-RS-001": ("UNLOAD ('SELECT * FROM users') TO 's3://bucket/';", "redshift"),
    "COST-SERVERLESS-001": ("SELECT * FROM users u JOIN orders o ON u.id = o.user_id JOIN products p ON o.product_id = p.id JOIN categories c ON p.cat_id = c.id JOIN suppliers s ON p.supplier_id = s.id GROUP BY u.id;", None),
    "COST-SERVERLESS-002": ("SET CONNECTION TIMEOUT=10000;", None),
    "COST-SF-001": ("SELECT * FROM snowflake_sample_data.tpch_sf100.lineitem;", "snowflake"),
    "COST-SF-002": ("COPY INTO mytable FROM @stage;", "snowflake"),
    "COST-SF-003": ("SELECT * FROM LATERAL FLATTEN(input => v);", "snowflake"),
    "COST-SPARK-001": ("SELECT /*+ BROADCAST(large_table) */ * FROM users JOIN large_table ON users.id = large_table.id;", "spark"),
    "COST-SPARK-002": ("CACHE TABLE users;", "spark"),
    "COST-STORAGE-001": ("CREATE TABLE t AS SELECT * FROM users;", None),
    "COST-TSQL-001": ("DECLARE cur CURSOR FOR SELECT * FROM users;", "tsql"),
    "MIG-BRK-001": ("DROP TABLE users;", None),
    "PERF-AGG-001": ("SELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1;", None),
    "PERF-AGG-002": ("SELECT * FROM (SELECT * FROM users ORDER BY name) sub;", None),
    "PERF-AGG-003": ("SELECT email FROM users HAVING COUNT(*) > 1;", None),
    "PERF-BATCH-001": ("DELETE FROM users;", None),
    "PERF-BATCH-002": ("WHILE 1=1 BEGIN UPDATE users SET name = 'x'; END", "tsql"),
    "PERF-BQ-001": ("SELECT DISTINCT * FROM UNNEST([1,2,3]) AS x;", "bigquery"),
    "PERF-BQ-002": ("SELECT * FROM t WHERE REGEXP_CONTAINS(col, 'pattern');", "bigquery"),
    "PERF-CH-001": ("SELECT * FROM users WHERE id = 1;", "clickhouse"),
    "PERF-CH-002": ("SELECT * FROM users JOIN orders ON users.id = orders.user_id;", "clickhouse"),
    "PERF-CH-003": ("ALTER TABLE users UPDATE SET name = 'x' WHERE id = 1;", "clickhouse"),
    "PERF-CURSOR-001": ("DECLARE cur CURSOR FOR SELECT * FROM users;", "tsql"),
    "PERF-CURSOR-002": ("WHILE @@FETCH_STATUS = 0 BEGIN FETCH NEXT FROM cur; END", "tsql"),
    "PERF-CURSOR-003": ("SELECT * FROM users LOOP JOIN orders ON users.id = orders.user_id;", "tsql"),
    "PERF-DUCK-001": ("COPY users TO 'output.csv';", "duckdb"),
    "PERF-DUCK-002": ("SELECT * FROM users WHERE id IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51);", "duckdb"),
    "PERF-HINT-001": ("SELECT * FROM users OPTION (FORCE ORDER, HASH JOIN);", "tsql"),
    "PERF-HINT-002": ("SELECT * FROM users FORCE INDEX (idx_email);", "mysql"),
    "PERF-HINT-003": ("SELECT * FROM users OPTION (MAXDOP 1);", "tsql"),
    "PERF-IDX-001": ("SELECT * FROM users WHERE LOWER(email) = 'test@test.com';", None),
    "PERF-IDX-002": ("SELECT * FROM users WHERE name LIKE '%john%';", None),
    "PERF-IDX-003": ("SELECT * FROM users WHERE id = '123';", None),
    "PERF-IDX-004": ("SELECT * FROM users WHERE id = 1 OR email = 'test@test.com';", None),
    "PERF-IDX-005": ("SELECT * FROM users ORDER BY name LIMIT 10 OFFSET 5000;", None),
    "PERF-IDX-006": ("SELECT * FROM orders WHERE created_at > '2024-01-01';", None),
    "PERF-IDX-007": ("SELECT * FROM users WHERE email = 'a' OR name = 'b';", None),
    "PERF-IDX-008": ("SELECT * FROM users WHERE COALESCE(email, 'a') = 'test';", None),
    "PERF-IDX-009": ("SELECT * FROM users WHERE email <> 'test';", None),
    "PERF-JOIN-001": ("SELECT * FROM users CROSS JOIN orders;", None),
    "PERF-JOIN-002": ("SELECT * FROM users u JOIN orders o ON u.id=o.user_id JOIN products p ON o.product_id=p.id JOIN categories c ON p.cat_id=c.id JOIN suppliers s ON p.supplier_id=s.id JOIN regions r ON s.region_id=r.id;", None),
    "PERF-JOIN-003": ("SELECT * FROM users u LEFT JOIN orders o ON u.id = o.user_id WHERE o.id IS NOT NULL;", None),
    "PERF-LOCK-001": ("SELECT * FROM users WITH (TABLOCK);", "tsql"),
    "PERF-LOCK-002": ("SELECT * FROM users WITH (NOLOCK);", "tsql"),
    "PERF-LOCK-003": ("BEGIN TRANSACTION; " + "UPDATE users SET name='x' WHERE id=1; "*50 + "COMMIT;", None),
    "PERF-LOCK-004": ("BEGIN TRANSACTION; UPDATE users SET name='x' WHERE id=1; COMMIT;", None),
    "PERF-MEM-001": ("SELECT * FROM users WHERE id IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51);", None),
    "PERF-MEM-002": ("SELECT * INTO #temp FROM users;", "tsql"),
    "PERF-MEM-003": ("SELECT * FROM (SELECT * FROM users ORDER BY name) sub;", None),
    "PERF-MEM-004": ("SELECT id, COUNT(*) FROM users GROUP BY id;", None),
    "PERF-MYSQL-001": ("SELECT * FROM users FOR UPDATE;", "mysql"),
    "PERF-MYSQL-002": ("SELECT * FROM users ORDER BY RAND();", "mysql"),
    "PERF-MYSQL-003": ("SELECT * FROM users FORCE INDEX (idx_email);", "mysql"),
    "PERF-MYSQL-004": ("SELECT email FROM users GROUP BY email;", "mysql"),
    "PERF-NET-001": ("SELECT col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14,col15,col16,col17,col18,col19,col20,col21 FROM users;", None),
    "PERF-NET-002": ("SELECT large_text FROM documents;", None),
    "PERF-ORA-001": ("SELECT * FROM users FOR UPDATE;", "oracle"),
    "PERF-PG-002": ("SELECT COUNT(*) FROM users;", "postgres"),
    "PERF-PG-003": ("SELECT * FROM users WHERE id NOT IN (SELECT id FROM orders);", "postgres"),
    "PERF-PG-004": ("SELECT * FROM users FOR UPDATE;", "postgres"),
    "PERF-PRESTO-001": ("SELECT * FROM users, orders;", "presto"),
    "PERF-RS-002": ("SELECT * FROM users ORDER BY name;", "redshift"),
    "PERF-RS-003": ("SELECT * FROM users WHERE id NOT IN (SELECT id FROM orders);", "redshift"),
    "PERF-SCALAR-001": ("SELECT dbo.my_func(id) FROM users;", "tsql"),
    "PERF-SCALAR-002": ("SELECT * FROM users u WHERE EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id);", None),
    "PERF-SCAN-001": ("SELECT * FROM users;", None),
    "PERF-SCAN-002": ("DELETE FROM users;", None),
    "PERF-SCAN-003": ("SELECT * FROM users ORDER BY name;", None),
    "PERF-SCAN-004": ("SELECT * FROM users WHERE id NOT IN (SELECT user_id FROM orders);", None),
    "PERF-SCAN-005": ("SELECT DISTINCT * FROM users;", None),
    "PERF-SF-001": ("SELECT * FROM users WHERE VARIANT_COL::string = 'test';", "snowflake"),
    "PERF-SF-002": ("SELECT * FROM users ORDER BY VARIANT_COL::string;", "snowflake"),
    "PERF-SORT-001": ("SELECT * FROM articles ORDER BY description;", None),
    "PERF-SPARK-001": ("SELECT /*+ BROADCAST(orders) */ * FROM users JOIN orders ON users.id = orders.user_id;", "spark"),
    "PERF-SPARK-002": ("SELECT * FROM users WHERE my_udf(id) = 1;", "spark"),
    "PERF-SQLITE-001": ("PRAGMA journal_mode = DELETE;", "sqlite"),
    "PERF-SQLITE-002": ("SELECT * FROM users WHERE name LIKE 'john%';", "sqlite"),
    "PERF-TSQL-001": ("CREATE PROCEDURE p AS BEGIN SELECT * FROM users; END;", "tsql"),
    "PERF-TSQL-002": ("SELECT * INTO #temp FROM users;", "tsql"),
    "PERF-TSQL-003": ("SELECT * FROM users u JOIN orders o ON CONVERT(VARCHAR, u.id) = CAST(o.user_id AS VARCHAR);", "tsql"),
    "PERF-TSQL-004": ("WAITFOR DELAY '00:00:05';", "tsql"),
    "QUAL-CH-001": ("SELECT * FROM users ORDER BY name;", "clickhouse"),
    "QUAL-COMPLEX-001": ("SELECT CASE WHEN x=1 THEN CASE WHEN y=1 THEN CASE WHEN z=1 THEN CASE WHEN w=1 THEN 'deep' END END END END FROM t;", None),
    "QUAL-COMPLEX-002": ("SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM users) s1) s2) s3;", None),
    "QUAL-COMPLEX-003": ("SELECT * FROM t1 JOIN t2 ON 1=1 JOIN t3 ON 1=1 JOIN t4 ON 1=1 JOIN t5 ON 1=1 JOIN t6 ON 1=1 JOIN t7 ON 1=1 JOIN t8 ON 1=1 JOIN t9 ON 1=1 JOIN t10 ON 1=1 JOIN t11 ON 1=1 JOIN t12 ON 1=1 JOIN t13 ON 1=1 JOIN t14 ON 1=1 JOIN t15 ON 1=1;", None),
    "QUAL-COMPLEX-004": ("CREATE PROCEDURE p AS BEGIN IF 1=1 SELECT 1; IF 1=1 SELECT 2; IF 1=1 SELECT 3; IF 1=1 SELECT 4; IF 1=1 SELECT 5; END;", "tsql"),
    "QUAL-COMPLEX-005": ("SELECT *\n" * 60 + "FROM users;", None),
    "QUAL-DBT-001": ("SELECT * FROM users WHERE id > 0;", None),
    "QUAL-DBT-002": ("SELECT * FROM {{ source('raw', 'users') }};", None),
    "QUAL-DEAD-001": ("CREATE VIEW v1 AS SELECT * FROM users;", None),
    "QUAL-DEAD-002": ("SELECT * FROM users u1 JOIN users u2 ON u1.id = u2.id;", None),
    "QUAL-DEAD-003": ("SELECT * FROM users; SELECT * FROM users;", None),
    "QUAL-DEBT-001": ("-- TODO: this is a debug note\nSELECT 1;", None),
    "QUAL-DEBT-002": ("CREATE TEMP TABLE t (id INT);", None),
    "QUAL-DOC-001": ("CREATE TABLE t (id INT);", None),
    "QUAL-DOC-002": ("SELECT * FROM users WHERE name = 'John';", None),
    "QUAL-DOC-003": ("SELECT *\n" * 30 + "FROM users;", None),
    "QUAL-DRY-001": ("SELECT * FROM users WHERE status = 'active' AND status = 'active';", None),
    "QUAL-DUCK-001": ("SELECT INTEGER(id) FROM users;", "duckdb"),
    "QUAL-MODERN-001": ("SELECT * FROM users, orders;", None),
    "QUAL-MODERN-002": ("SELECT * FROM users WHERE created_at > '2024-01-01';", None),
    "QUAL-MODERN-003": ("SELECT id FROM users UNION SELECT id FROM orders;", None),
    "QUAL-MODERN-004": ("SELECT CASE WHEN id = 1 THEN 'a' END FROM users;", None),
    "QUAL-MYSQL-001": ("SELECT SQL_CALC_FOUND_ROWS * FROM users;", "mysql"),
    "QUAL-MYSQL-002": ("SELECT * FROM users STRAIGHT_JOIN orders;", "mysql"),
    "QUAL-MYSQL-003": ("SELECT * FROM users WHERE name = 'test' LOCK IN SHARE MODE;", "mysql"),
    "QUAL-NAME-001": ("SELECT * FROM user, orders;", None),
    "QUAL-NAME-002": ("SELECT u.email, o.total FROM users u JOIN orders o ON u.id = o.user_id;", None),
    "QUAL-NAME-003": ("SELECT str_name FROM tbl_users;", None),
    "QUAL-NAME-004": ("SELECT * FROM order;", None),
    "QUAL-NULL-001": ("SELECT * FROM users WHERE id = NULL;", None),
    "QUAL-ORA-001": ("SELECT * FROM users WHERE ROWNUM <= 10;", "oracle"),
    "QUAL-ORA-002": ("SELECT 1 FROM DUAL;", "oracle"),
    "QUAL-ORA-003": ("SELECT * FROM users WHERE NVL(email, 'a') = 'test';", "oracle"),
    "QUAL-PG-001": ("DO $$ BEGIN SELECT 1; END; $$;", "postgres"),
    "QUAL-PG-002": ("SELECT data  ->> 'key' FROM users;", "postgres"),
    "QUAL-RS-001": ("CREATE TABLE t (id INT) DISTSTYLE ALL;", "redshift"),
    "QUAL-SCHEMA-001": ("CREATE TABLE t (id INT);", None),
    "QUAL-SCHEMA-002": ("CREATE TABLE orders (user_id INT);", None),
    "QUAL-SCHEMA-003": ("CREATE TABLE orders (user_id INT REFERENCES users(id));", None),
    "QUAL-SCHEMA-004": ("CREATE TABLE products (price FLOAT);", None),
    "QUAL-SF-001": ("SELECT * FROM LATERAL FLATTEN();", "snowflake"),
    "QUAL-SQLITE-001": ("CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT);", "sqlite"),
    "QUAL-STYLE-001": ("SELECT 1;", None),
    "QUAL-STYLE-002": ("EXISTS (SELECT * FROM users WHERE id = 1);", None),
    "QUAL-STYLE-003": ("SELECT * FROM (SELECT * FROM users) WHERE id = 1;", None),
    "QUAL-STYLE-004": ("-- SELECT * FROM users\n", None),
    "QUAL-STYLE-005": ("INSERT INTO users VALUES (1, 'a');", None),
    "QUAL-TEST-001": ("SELECT * FROM users WHERE created_at = NOW();", None),
    "QUAL-TEST-002": ("SELECT * FROM users LIMIT 10;", None),
    "QUAL-TEST-003": ("SELECT * FROM users WHERE name = 'test';", None),
    "QUAL-TSQL-001": ("SET ANSI_NULLS OFF;", "tsql"),
    "QUAL-TSQL-002": ("SET QUOTED_IDENTIFIER OFF;", "tsql"),
    "REL-BQ-001": ("DELETE FROM project.dataset.table;", "bigquery"),
    "REL-CH-001": ("SELECT * FROM users;", "clickhouse"),
    "REL-DATA-001": ("DELETE FROM users;", None),
    "REL-DATA-002": ("TRUNCATE TABLE users;", None),
    "REL-DATA-003": ("ALTER TABLE users DROP COLUMN email;", None),
    "REL-DATA-004": ("DROP TABLE users;", None),
    "REL-DEAD-001": ("BEGIN; UPDATE users SET name='x'; UPDATE orders SET total=0; COMMIT;", None),
    "REL-DEAD-002": ("DELETE FROM orders WHERE created_at < '2020-01-01';", None),
    "REL-ERR-001": ("BEGIN EXCEPTION WHEN OTHERS THEN NULL; END;", "oracle"),
    "REL-FK-001": ("INSERT INTO orders (user_id, total) VALUES (999, 100);", None),
    "REL-FK-002": ("DELETE FROM users WHERE id = 1;", None),
    "REL-IDEM-001": ("INSERT INTO users (email) VALUES ('a@b.com');", None),
    "REL-IDEM-002": ("UPDATE users SET counter = counter + 1 WHERE id = 1;", None),
    "REL-MYSQL-001": ("INSERT IGNORE INTO users VALUES (1);", "mysql"),
    "REL-MYSQL-002": ("REPLACE INTO users (id) VALUES (1);", "mysql"),
    "REL-MYSQL-003": ("CREATE TABLE t (name VARCHAR(10) CHARACTER SET utf8);", "mysql"),
    "REL-MYSQL-004": ("CREATE TABLE t (id INT, FOREIGN KEY (id) REFERENCES parent(id) ON UPDATE CASCADE);", "mysql"),
    "REL-MYSQL-005": ("CREATE TABLE users (id INT) ENGINE = MyISAM;", "mysql"),
    "REL-ORA-001": ("SELECT * FROM users CONNECT BY PRIOR id = parent_id;", "oracle"),
    "REL-ORA-002": ("ALTER TABLE users MOVE;", "oracle"),
    "REL-ORA-003": ("PRAGMA AUTONOMOUS_TRANSACTION;", "oracle"),
    "REL-PG-001": ("ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT now();", "postgres"),
    "REL-PG-002": ("CREATE INDEX idx ON users(id);", "postgres"),
    "REL-PRESTO-001": ("INSERT OVERWRITE TABLE users SELECT * FROM staging_users;", "presto"),
    "REL-RACE-001": ("SELECT balance FROM accounts WHERE id = 1; UPDATE accounts SET balance = balance - 100 WHERE id = 1;", None),
    "REL-RACE-002": ("IF EXISTS (SELECT 1 FROM users WHERE id=1) UPDATE users SET name='x' WHERE id=1;", None),
    "REL-REC-001": ("BEGIN; SAVEPOINT sp1; INSERT INTO t1 VALUES (1); INSERT INTO t1 VALUES (2); INSERT INTO t1 VALUES (3); COMMIT;", None),
    "REL-RETRY-001": ("BEGIN TRANSACTION; SELECT 1; COMMIT;", None),
    "REL-RS-001": ("COPY users FROM 's3://bucket/data/' CREDENTIALS '...';", "redshift"),
    "REL-SF-001": ("COPY INTO users FROM @stage;", "snowflake"),
    "REL-SPARK-001": ("INSERT OVERWRITE TABLE users SELECT * FROM staging_users;", "spark"),
    "REL-SQLITE-001": ("ALTER TABLE users DROP COLUMN email;", "sqlite"),
    "REL-SQLITE-002": ("PRAGMA foreign_keys = OFF;", "sqlite"),
    "REL-STALE-001": ("INSERT INTO users (id) VALUES (1); SELECT * FROM users;", None),
    "REL-TIMEOUT-001": ("SELECT * FROM users u JOIN orders o ON u.id = o.user_id JOIN products p ON o.product_id = p.id JOIN categories c ON p.cat_id = c.id;", None),
    "REL-TSQL-001": ("SELECT @@IDENTITY;", "tsql"),
    "REL-TSQL-002": ("MERGE INTO users USING src ON users.id = src.id WHEN MATCHED THEN UPDATE SET name = src.name;", "tsql"),
    "REL-TSQL-003": ("BEGIN TRY TRUNCATE TABLE users; END TRY", "tsql"),
    "REL-TXN-001": ("BEGIN; UPDATE users SET name='x'; COMMIT;", None),
    "REL-TXN-002": ("SET autocommit = 0;", None),
    "REL-TXN-003": ("BEGIN; COMMIT;", None),
    "SCH-BRK-001": ("ALTER TABLE orders DROP COLUMN total;", None),
    "SCHEMA-COL-001": ("SELECT nonexistent_col FROM users;", None),
    "SCHEMA-IDX-001": ("SELECT * FROM users WHERE email = 'test@test.com';", None),
    "SCHEMA-TBL-001": ("SELECT * FROM nonexistent_table;", None),
    "SEC-AUTH-001": ("SELECT * FROM users WHERE password = 'hardcoded123';", None),
    "SEC-AUTH-002": ("GRANT SELECT ON users TO PUBLIC;", None),
    "SEC-AUTH-003": ("CREATE USER testuser;", None),
    "SEC-AUTH-004": ("CREATE LOGIN x WITH PASSWORD = 'x', CHECK_POLICY = OFF;", "tsql"),
    "SEC-AUTH-005": ("GRANT ALL PRIVILEGES ON users TO admin;", None),
    "SEC-AUTHZ-001": ("GRANT ALL ON users TO admin;", None),
    "SEC-AUTHZ-002": ("ALTER AUTHORIZATION ON SCHEMA::dbo TO guest;", "tsql"),
    "SEC-AUTHZ-003": ("SELECT * FROM orders;", None),
    "SEC-CFG-001": ("sp_configure 'xp_cmdshell', 1;", "tsql"),
    "SEC-CH-001": ("SELECT * FROM url('http://evil.com/data.csv');", "clickhouse"),
    "SEC-CMD-001": ("xp_cmdshell 'ls -la';", "tsql"),
    "SEC-CMD-001-PG": ("SELECT pg_read_file('/etc/passwd');", "postgres"),
    "SEC-CONFIG-001": ("CREATE USER admin IDENTIFIED BY 'password123';", None),
    "SEC-CONFIG-002": ("Encrypt=false;TrustServerCertificate=true;", None),
    "SEC-CONFIG-003": ("CREATE USER sa IDENTIFIED BY 'sa';", None),
    "SEC-CONFIG-004": ("GRANT ALL TO 'user'@'%';", "mysql"),
    "SEC-CRYPTO-001": ("SELECT MD5(password) FROM users;", None),
    "SEC-CRYPTO-002": ("INSERT INTO users (password) VALUES ('plaintext');", None),
    "SEC-CRYPTO-003": ("SELECT AES_ENCRYPT('data', 'mysecretkey12345') FROM t;", "mysql"),
    "SEC-CRYPTO-004": ("SELECT DES_ENCRYPT('secret', 'key');", "mysql"),
    "SEC-DATA-001": ("SELECT * FROM users INTO OUTFILE '/tmp/dump.txt';", "mysql"),
    "SEC-DATA-002": ("SELECT * FROM OPENROWSET('SQLOLEDB', 'srv', 'sa', 'pw', 'query');", "tsql"),
    "SEC-DOS-001": ("WITH cte AS (SELECT 1 UNION ALL SELECT 1 FROM cte) SELECT * FROM cte;", None),
    "SEC-DOS-002": ("SELECT * FROM users WHERE name REGEXP '(a+)+b';", "mysql"),
    "SEC-INFO-001": ("SELECT @@VERSION;", None),
    "SEC-INFO-002": ("SELECT * FROM INFORMATION_SCHEMA.TABLES;", None),
    "SEC-INFO-003": ("SELECT SLEEP(5);", None),
    "SEC-INFO-004": ("RAISERROR('error', 16, 1, @@ERROR);", "tsql"),
    "SEC-INJ-001": ("SELECT * FROM users WHERE name = 'x' + user_input;", None),
    "SEC-INJ-002": ("EXECUTE IMMEDIATE 'SELECT * FROM users WHERE id = ' || user_id;", None),
    "SEC-INJ-003": ("SELECT * FROM users WHERE id = 1 OR 1=1;", None),
    "SEC-INJ-004": ("SELECT SLEEP(5) FROM dual;", None),
    "SEC-INJ-005": ("INSERT INTO users (username) VALUES ('test');", None),
    "SEC-INJ-006": ("SELECT * FROM users WHERE name LIKE :input;", None),
    "SEC-INJ-007": ("SELECT * FROM t WHERE LDAP_QUERY('cn=' || input);", None),
    "SEC-INJ-008": ("SELECT JSON_VALUE(data, '$.name' || '{evil}') FROM t", None),
    "SEC-INJ-009": ("SELECT XMLEXISTS('//data' || input) FROM t;", None),
    "SEC-INJ-010": ("SELECT RENDER_TEMPLATE('hello' || user_input) FROM t;", None),
    "SEC-INJ-011": ("SELECT JSON_OBJECT('key' || user_input) FROM t;", None),
    "SEC-LOG-001": ("RAISERROR('password is %s', 16, 1, @pwd);", "tsql"),
    "SEC-LOG-002": ("DELETE FROM audit_log WHERE id = 1;", None),
    "SEC-MYSQL-001": ("LOAD DATA LOCAL INFILE '/etc/passwd' INTO TABLE t;", "mysql"),
    "SEC-ORA-001": ("SELECT UTL_HTTP.REQUEST('http://evil.com') FROM dual;", "oracle"),
    "SEC-ORA-002": ("DBMS_SQL.PARSE(cursor, query, 1);", "oracle"),
    "SEC-ORA-003": ("EXECUTE IMMEDIATE 'SELECT ' || user_input;", "oracle"),
    "SEC-PATH-001": ("SELECT LOAD_FILE(CONCAT('../etc/passwd')) FROM users;", "mysql"),
    "SEC-PATH-002": ("EXEC('source ' || user_input || '.sql');", None),
    "SEC-PG-001": ("SELECT pg_sleep(5);", "postgres"),
    "SEC-PG-002": ("SET search_path = public;", "postgres"),
    "SEC-PG-003": ("RAISE NOTICE 'data: ' || password;", "postgres"),
    "SEC-PG-004": ("CREATE FUNCTION f() RETURNS INT AS $$ BEGIN RETURN 1; END; $$ LANGUAGE plpgsql SECURITY DEFINER;", "postgres"),
    "SEC-PRIV-001": ("EXECUTE AS USER = 'dbo';", "tsql"),
    "SEC-RS-001": ("COPY t FROM 's3://bucket/data' CREDENTIALS 'ACCESS_KEY_ID=x;SECRET_ACCESS_KEY=y';", "redshift"),
    "SEC-SESSION-001": ("INSERT INTO sessions (session_token) VALUES ('abc12345678901234567890');", None),
    "SEC-SESSION-002": ("SELECT * FROM sessions WHERE session_id = 'abc';", None),
    "SEC-SF-001": ("COPY INTO t FROM @stage CREDENTIALS = (AWS_KEY_ID='x' AWS_SECRET_KEY='y');", "snowflake"),
    "SEC-SF-002": ("CREATE TABLE t_clone CLONE t;", "snowflake"),
    "SEC-SQLITE-001": ("ATTACH DATABASE '/etc/passwd' AS ext;", "sqlite"),
    "SEC-SSRF-001": ("SELECT UTL_HTTP.REQUEST('http://evil.com') FROM dual;", "oracle"),
    "SEC-TSQL-001": ("SELECT * FROM OPENROWSET('SQLOLEDB', 'srv', 'sa', 'pw', 'q');", "tsql"),
    "SEC-TSQL-002": ("sp_OACreate 'Scripting.FileSystemObject', @obj OUT;", "tsql"),
}
